kind: pipeline
type: docker
name: default

steps:
  - name: build_war
    image: maven:3.6.3-jdk-8-slim
    commands:
      - mvn --batch-mode package --file pom.xml

  - name: build_docker_image
    image: plugins/docker
    settings:
      username: hsmtkk
      password:
        from_secret: GITHUB_TOKEN
      repo: docker.pkg.github.com/hsmtkk/hello-world/hello-world
      registry: docker.pkg.github.com
      auto_tag: true
